### ISSUE TITLE
Web entities list pagination + selection

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe#303] opened 2019-04-04 16:39 UTC
To replicate:
Go to web entities list
search something which replies a long list of WE
select the first two (you should see the cart/action box)
then scroll enough to tigger a pagination call
try to select a few more 
=> the selection is not added to the cart.

Alternative scenario.
Don't select before scrolling to paginate.
If you select after pagination, the cart/action box does not appear at all.

Looks like the pagination call breaks the event listener of selection actions ?

**Comment by boogheta** [comment] 2019-06-05 15:00
can't reproduce anymore, let's assume it was fixed by border effect and reopen if we encounter it again ;)

**Closed by boogheta** 2019-06-05 15:00 UTC
Labels: bug, web interface
