### ISSUE TITLE
Indexer seems to crash

### ISSUE THREAD

**Issue by JoshuaJoma** [medialab/hyphe#250] opened 2018-02-02 17:14 UTC
Hi, 

did a Docker-Install on a fresh Kubuntu 16.04 install 2 weeks ago and started working on a corpus. 

Since two days, every time i start the corpus it stays at the same numbers of pages to index.  After some time the systems runs out of memory. 

The log says:
backend_1   | 2018-02-02 16:41:44+0000 [INFO - fm-welt] Starting corpus...
backend_1   | 2018-02-02 16:41:44+0000 [INFO - fm-welt] WARNING: PID file already exists for traph-sockets/fm-welt, cleaning-up...
backend_1   | 2018-02-02 16:41:44+0000 [INFO - fm-welt] Removing residual socket file traph-sockets/fm-welt
backend_1   | 2018-02-02 16:41:44+0000 [INFO - fm-welt] Starting Traph for at least 6596s: /usr/local/bin/python -u hyphe_backend/traph/server.py traph-sockets/fm-welt fm-welt
backend_1   | 2018-02-02 16:41:44+0000 [-] Starting factory <hyphe_backend.traph.client.TraphClientFactory instance at 0x7f46d9a3a3b0>
backend_1   | 2018-02-02 16:41:44+0000 [INFO - fm-welt] Traph ready
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:45 +0000] "POST /api/ HTTP/1.1" 200 211 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:45 +0000] "POST /api/ HTTP/1.1" 200 1701 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:45 +0000] "POST /api/ HTTP/1.1" 200 91 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:45 +0000] "POST /api/ HTTP/1.1" 200 39 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
backend_1   | 2018-02-02 16:41:45+0000 [WARNING - fm-welt] Indexing job declared as running but probably crashed, trying to restart it.
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:45 +0000] "POST /api/ HTTP/1.1" 200 7874 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:45 +0000] "POST /api/ HTTP/1.1" 200 151967 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
crawler_1   | 2018-02-02T16:41:45+0000 [twisted.python.log#info] "172.18.0.4" - - [02/Feb/2018:16:41:45 +0000] "GET /listjobs.json?project=hyphe_fm-welt HTTP/1.0" 200 63 "-" "Twisted PageGetter"
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:47 +0000] "POST /api/ HTTP/1.1" 200 7886 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:48 +0000] "POST /api/ HTTP/1.1" 200 7886 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
mongo_1     | 2018-02-02T16:41:49.274+0000 I COMMAND  [conn64] query hyphe_fm-welt.queue query: { $orderby: { timestamp: 1 }, $query: { _job: "ae534805054011e8bfd20242ac120004" } } planSummary: IXSCAN { _job: 1, timestamp: -1 } cursorid:116273297489 ntoreturn:250 ntoskip:0 nscanned:101 nscannedObjects:101 keyUpdates:0 writeConflicts:0 numYields:74 nreturned:4 reslen:5019369 locks:{ Global: { acquireCount: { r: 150 } }, MMAPV1Journal: { acquireCount: { r: 75 } }, Database: { acquireCount: { r: 75 } }, Collection: { acquireCount: { R: 75 } } } 3366ms
mongo_1     | 2018-02-02T16:41:50.490+0000 I COMMAND  [conn64] getmore hyphe_fm-welt.queue query: { _job: "ae534805054011e8bfd20242ac120004" } cursorid:116273297489 ntoreturn:246 keyUpdates:0 writeConflicts:0 numYields:3 nreturned:4 reslen:5006892 locks:{ Global: { acquireCount: { r: 8 } }, MMAPV1Journal: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 4 } }, Collection: { acquireCount: { R: 4 } } } 998ms
mongo_1     | 2018-02-02T16:41:50.766+0000 I COMMAND  [conn73] command hyphe_fm-welt.$cmd command: count { count: "pages", query: { _job: "d2ddc828054011e899ea0242ac120004", forgotten: { $ne: true } } } planSummary: IXSCAN { _job: 1 } ntoreturn:1 keyUpdates:0 writeConflicts:0 numYields:137 reslen:44 locks:{ Global: { acquireCount: { r: 276 } }, MMAPV1Journal: { acquireCount: { r: 138 } }, Database: { acquireCount: { r: 138 } }, Collection: { acquireCount: { R: 138 } } } 4768ms
mongo_1     | 2018-02-02T16:41:51.059+0000 I COMMAND  [conn76] command hyphe_fm-welt.$cmd command: count { count: "queue", query: { _job: "d2ddc828054011e899ea0242ac120004" } } planSummary: COUNT_SCAN { _job: 1, timestamp: -1 } ntoreturn:1 keyUpdates:0 writeConflicts:0 numYields:1 reslen:44 locks:{ Global: { acquireCount: { r: 4 } }, MMAPV1Journal: { acquireCount: { r: 2 } }, Database: { acquireCount: { r: 2 } }, Collection: { acquireCount: { R: 2 } } } 292ms
mongo_1     | 2018-02-02T16:41:51.763+0000 I COMMAND  [conn64] getmore hyphe_fm-welt.queue query: { _job: "ae534805054011e8bfd20242ac120004" } cursorid:116273297489 ntoreturn:242 keyUpdates:0 writeConflicts:0 numYields:3 nreturned:4 reslen:5037824 locks:{ Global: { acquireCount: { r: 8 } }, MMAPV1Journal: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 4 } }, Collection: { acquireCount: { R: 4 } } } 1066ms
mongo_1     | 2018-02-02T16:41:52.934+0000 I COMMAND  [conn64] getmore hyphe_fm-welt.queue query: { _job: "ae534805054011e8bfd20242ac120004" } cursorid:116273297489 ntoreturn:238 keyUpdates:0 writeConflicts:0 numYields:3 nreturned:4 reslen:5165012 locks:{ Global: { acquireCount: { r: 8 } }, MMAPV1Journal: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 4 } }, Collection: { acquireCount: { R: 4 } } } 943ms
mongo_1     | 2018-02-02T16:41:53.729+0000 I COMMAND  [conn81] query hyphe_fm-welt.jobs query: { $orderby: { crawling_status: 1, indexing_status: 1, created_at: 1 }, $query: { webentity_id: { $in: [ 3, 1, 7, 13, 17, 16, 18, 19, 20, 21, 22, 23, 24, 25, 27, 32, 33, 34, 14791, 42, 46, 48, 11778, 161, 243, 269, 308, 321, 347, 357, 364, 375, 391, 409, 479, 491, 506, 519, 559, 563, 638, 653, 656, 678, 824, 12, 4, 5, 6, 10, 8, 9, 11, 26, 14, 15, 30, 31, 28, 1133, 1188, 29, 271, 1370, 657, 695, 644, 1444, 242, 255, 171, 226, 267, 274, 14790, 549, 285, 600, 664, 665, 511, 705, 1716, 1726, 1745, 823, 888, 1067, 1118, 1393, 1793, 1818, 1864, 1863, 340, 2246, 335, 341, 363, 658 ] } } } planSummary: IXSCAN { webentity_id: 1 } ntoreturn:0 ntoskip:0 nscanned:127 nscannedObjects:85 scanAndOrder:1 keyUpdates:0 writeConflicts:0 numYields:8 nreturned:85 reslen:10985 locks:{ Global: { acquireCount: { r: 18 } }, MMAPV1Journal: { acquireCount: { r: 9 } }, Database: { acquireCount: { r: 9 } }, Collection: { acquireCount: { R: 9 } } } 151ms
mongo_1     | 2018-02-02T16:41:54.784+0000 I COMMAND  [conn80] insert hyphe_fm-welt.queries ninserted:1 keyUpdates:0 writeConflicts:0 numYields:0 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, MMAPV1Journal: { acquireCount: { w: 2 }, acquireWaitCount: { w: 1 }, timeAcquiringMicros: { w: 37 } }, Database: { acquireCount: { w: 1 } }, Collection: { acquireCount: { W: 1 } } } 254ms
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:54 +0000] "POST /api/ HTTP/1.1" 200 64744 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
mongo_1     | 2018-02-02T16:41:54.793+0000 I COMMAND  [conn64] getmore hyphe_fm-welt.queue query: { _job: "ae534805054011e8bfd20242ac120004" } cursorid:116273297489 ntoreturn:234 keyUpdates:0 writeConflicts:0 numYields:3 nreturned:4 reslen:5007405 locks:{ Global: { acquireCount: { r: 8 } }, MMAPV1Journal: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 4 } }, Collection: { acquireCount: { R: 4 } } } 1630ms
mongo_1     | 2018-02-02T16:41:55.139+0000 I COMMAND  [conn83] query hyphe_fm-welt.webentities query: { _id: { $in: [ 889, 956, 1374, 2541, 2612, 2655, 268, 1735, 706, 2077, 2785, 2794, 885, 954, 1641, 1901, 3015, 3047, 1753, 1648, 1429, 252, 349, 470, 286, 891, 1900, 1787, 1672, 1714, 1913, 40, 54, 11785, 11793, 57, 145, 186, 208, 210, 215, 241, 302, 330, 332, 369, 472, 11957, 377, 564, 586, 11978, 632, 660, 641, 668, 788, 886, 887, 890, 912, 980, 994, 1010, 1107, 1152, 12107, 1215, 12139, 12141, 1267, 1315, 1378, 1420, 1421, 1428, 1522, 1678, 1702, 1717, 1722, 1727, 1739, 1732, 1775, 1773, 1785, 1792, 1861, 1862, 1939, 2078, 2081, 2368, 2289, 2472, 2522, 13171, 2677, 2867 ] } } planSummary: IXSCAN { _id: 1 } ntoreturn:0 ntoskip:0 nscanned:190 nscannedObjects:100 keyUpdates:0 writeConflicts:0 numYields:3 nreturned:100 reslen:70142 locks:{ Global: { acquireCount: { r: 8 } }, MMAPV1Journal: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 4 } }, Collection: { acquireCount: { R: 4 } } } 203ms
frontend_1  | 172.18.0.1 - - [02/Feb/2018:16:41:55 +0000] "POST /api/ HTTP/1.1" 200 78193 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"

What could be a solution?

Thanks.

Uwe

**Comment by boogheta** [comment] 2018-02-09 14:08
Hi @JoshuaJoma 
I miss more elements and don't really understand what is the issue there. Apart from the fact an indexation was apparently still running when hyphe was previously stopped and that it is handling it, there are no errors in the above logs.

You say the system runs out of memory, what do you mean exactly and how do you diagnose this?
In any case, Hyphe is a bit havy consuming, and you should indeed run it preferable with at least a few gigs of ram as well as hard drive available.

**Comment by JoshuaJoma** [comment] 2018-02-12 17:47
Hi boogheta,

thanks for your reply.
After letting hyphe do indexation for more than 2 days on this corpus it didn't even index one more page. Instead my 4gb of ram are fully occupied by processes called python, web and mongod. Space on my hdd is more than enough.
I tried if the corpus might be to big but i reproduced the corpus from a backup-file and continued working on it without problems. 
Because i aimed for a first overview of a network i used crawling depth of 3. Might this be a reason for to many pages to index?
What log-files do you need?

Best,
Uwe

**Comment by boogheta** [comment] 2018-02-13 12:46
Well, that is definitely  not normal :/
I don't really know where to start... For a start, I could use a full log of your docker containers, as well as some metrics on your data volumes (using `docker volume inspect hyphe_mongo-data` and `docker volume inspect hyphe_traph-data` to identify where they are in your filesystem, and then `sudo ls -lrth VOLUMEPATH` with VOLUMEPATH being the `Mountpoint` obtained from the previous commands.

**Comment by Yomguithereal** [comment] 2018-02-13 13:13
Hello @JoshuaJoma. Can you somehow give us the urls you used to seed the crawl so we can eventually try and replicate on our own?

**Comment by JoshuaJoma** [comment] 2018-02-21 19:49
Hi @boogheta,

here are the logs. The corpus were the problem occurs is called fm-welt. fmwelt is the corpus i created from the backup of fm-welt. The others are just tests. 

Output of:
sudo ls -lrth /var/lib/docker/volumes/hyphe_mongo-data/_data

insgesamt 23G
-rw-r--r-- 1 999 docker   69 Jan 22 19:00 storage.bson
-rw------- 1 999 docker 512M Jan 22 21:43 hyphe_fm-verbaende.3
-rw------- 1 999 docker  16M Jan 22 21:43 hyphe_fm-verbaende.ns
-rw------- 1 999 docker 256M Jan 22 21:43 hyphe_fm-verbaende.2
-rw------- 1 999 docker  64M Jan 22 21:43 hyphe_fm-verbaende.0
-rw------- 1 999 docker 128M Jan 22 21:43 hyphe_fm-verbaende.1
-rw------- 1 999 docker  16M Jan 22 21:54 hyphe_fm-verbaende2.ns
-rw------- 1 999 docker  64M Jan 22 21:54 hyphe_fm-verbaende2.0
-rw------- 1 999 docker 128M Jan 23 00:21 hyphe_fm_verbaende3.1
-rw------- 1 999 docker  16M Jan 23 00:26 hyphe_fm_verbaende3.ns
-rw------- 1 999 docker 512M Jan 23 00:26 hyphe_fm_verbaende3.3
-rw------- 1 999 docker 256M Jan 23 00:26 hyphe_fm_verbaende3.2
-rw------- 1 999 docker  64M Jan 23 00:26 hyphe_fm_verbaende3.0
-rw------- 1 999 docker 2,0G Jan 30 03:19 hyphe_fm-welt.7                                                                                                                   
-rw------- 1 999 docker 128M Feb  2 18:21 hyphe_fm-welt.1                                                                                                                   
-rw------- 1 999 docker 2,0G Feb  2 18:21 hyphe_fm-welt.9                                                                                                                   
-rw------- 1 999 docker 2,0G Feb  2 23:56 hyphe_fm-welt.6                                                                                                                   
-rw------- 1 999 docker 256M Feb  2 23:56 hyphe_fm-welt.2                                                                                                                   
-rw------- 1 999 docker 1,0G Feb  2 23:56 hyphe_fm-welt.4                                                                                                                   
-rw------- 1 999 docker  16M Feb  2 23:56 hyphe_fm-welt.ns
-rw------- 1 999 docker 2,0G Feb  2 23:56 hyphe_fm-welt.8
-rw------- 1 999 docker 2,0G Feb  2 23:56 hyphe_fm-welt.5
-rw------- 1 999 docker 512M Feb  2 23:56 hyphe_fm-welt.3
-rw------- 1 999 docker  64M Feb  2 23:56 hyphe_fm-welt.0
-rw------- 1 999 docker 256M Feb 12 23:24 hyphe_fmwelt2.2
-rw------- 1 999 docker 2,0G Feb 12 23:24 hyphe_fmwelt2.6
-rw------- 1 999 docker 2,0G Feb 12 23:24 hyphe_fmwelt2.5
-rw------- 1 999 docker 512M Feb 12 23:26 hyphe_fmwelt2.3
-rw------- 1 999 docker  16M Feb 12 23:26 hyphe_fmwelt2.ns
-rw------- 1 999 docker 1,0G Feb 12 23:26 hyphe_fmwelt2.4
-rw------- 1 999 docker 128M Feb 12 23:26 hyphe_fmwelt2.1
-rw------- 1 999 docker 2,0G Feb 12 23:26 hyphe_fmwelt2.7
-rw------- 1 999 docker  64M Feb 12 23:26 hyphe_fmwelt2.0
-rw-r--r-- 1 999 docker    2 Feb 21 17:29 mongod.lock
-rw------- 1 999 docker  16M Feb 21 17:29 local.ns
-rw------- 1 999 docker  64M Feb 21 17:29 local.0
-rw------- 1 999 docker  16M Feb 21 17:29 hyphe.ns
-rw------- 1 999 docker  16M Feb 21 17:29 hyphe_--test-corpus--.ns
-rw------- 1 999 docker  64M Feb 21 17:29 hyphe_--test-corpus--.0
drwxr-xr-x 2 999 docker 4,0K Feb 21 17:30 journal
-rw------- 1 999 docker  64M Feb 21 17:37 hyphe.0


Output of:
sudo ls -lrth /var/lib/docker/volumes/hyphe_traph-data/_data

drwxr-xr-x 2 root root 4,0K Jan 22 19:05 --test-corpus--
drwxr-xr-x 2 root root 4,0K Jan 22 19:05 fm-verbaende
drwxr-xr-x 2 root root 4,0K Jan 22 21:47 fm-verbaende2
drwxr-xr-x 2 root root 4,0K Jan 22 22:55 fm_verbaende3
drwxr-xr-x 2 root root 4,0K Jan 23 20:25 fm-welt
drwxr-xr-x 2 root root 4,0K Feb  3 15:39 fmwelt2

Let me know if you need something else.

Best,
Uwe

**Comment by JoshuaJoma** [comment] 2018-02-21 19:51
Hi @Yomguithereal 

i can send the list but i would prefer to send it to you via mail. 

Best,
Uwe

**Comment by Yomguithereal** [comment] 2018-02-22 11:50
You can try to send this to myname.mysurname [at] sciencespo.fr

**Comment by boogheta** [comment] 2018-02-22 16:46
Hey @JoshuaJoma 
If we could try and reproduce your corpus as explained as suggested by @Yomguithereal, it will indeed certainly help.
Looking at the size of your databases, it looks like fmwelt2 is nearly as big as fm_welt, but my understanding is you don't have the same issue with it? In which case it really sounds like it is a specific issue due to you corpus, but again I'm not sure what it can be.
Can you try and give me the number of elements of each collection of hte dediocated mlongo database? Something along:
```bash
for coll in jobs logs queue pages webentities; do
  echo $coll; docker-compose exec mongo mongo 'hyphe_fm-welt' --quiet --eval "db['$coll'].count()" 2> /dev/null;
done
```

**Comment by JoshuaJoma** [comment] 2018-02-28 13:39
The Output of 
```
for coll in jobs logs queue pages webentities; do
  echo $coll; docker-compose exec mongo mongo 'hyphe_fm-welt' --quiet --eval "db['$coll'].count()" 2> /dev/null;
done
```
after I started the corpus FM-Welt is only 

> jobs
> logs
> queue
> pages
> webentities

Nothing else. 
After stopping docker it's the same.

**Comment by boogheta** [comment] 2018-03-05 13:42
That is weird, it should at least display zeros for each table such as 
```
jobs
0
logs
0
queue
0
pages
0
webentities
0
```

So maybe calling mongo via docker-compose doesn not work properly and it is hidden since my command was trashing stderr, can you rerun the same without the 2> /dev/null part?
```bash
for coll in jobs logs queue pages webentities; do
  echo $coll
  docker-compose exec mongo mongo 'hyphe_fm-welt' --quiet --eval "db['$coll'].count()"
done
```

**Comment by JoshuaJoma** [comment] 2018-03-09 14:55
Then the output is:

jobs
228
logs
27446
queue
5243
pages
85682
webentities
21498

**Comment by boogheta** [comment] 2019-08-06 16:02
Hi @JoshuaJoma and apologies for not investigating further back then, we really could not see where the problem would come from.
Hyphe has changed quite a bit since then and I feel like this issue becomes quite outdated now, so I'm closing it, but please reopen another one if you encounter similar things with a recent version.

**Closed by boogheta** 2019-08-06 16:02 UTC
Labels: bug, memory structure
